pallets/spacewalk/src/tests.rs

add test cases for extrinsics

---

Cargo.lock
testchain/node/src/chain_spec.rs
testchain/runtime/Cargo.toml
testchain/runtime/src/lib.rs

strip down testchain runtime

---

Cargo.lock
clients/runtime/Cargo.toml
clients/vault/Cargo.toml
pallets/spacewalk/Cargo.lock
pallets/spacewalk/Cargo.toml
testchain/node/Cargo.toml
testchain/node/src/service.rs
testchain/primitives/Cargo.toml
testchain/rpc/Cargo.toml
testchain/runtime/Cargo.toml

59 bump polkadot version to v0918

---

pallets/spacewalk/src/lib.rs
pallets/spacewalk/src/tests.rs

from: https://github.com/pendulum-chain/spacewalk/pull/63
but this PR is to merge to `main` branch.

Make redeem() accepts Stellar encoded addresses (#63)

---

.gitignore
clients/runtime/client/src/lib.rs
clients/runtime/src/cli.rs
clients/runtime/src/integration/mod.rs
clients/runtime/src/lib.rs
clients/runtime/src/rpc.rs
clients/runtime/src/types.rs
clients/vault/tests/vault_integration_tests.rs
pallets/spacewalk/src/address_conv.rs
pallets/spacewalk/src/lib.rs
pallets/spacewalk/src/tests.rs
testchain/runtime/src/lib.rs

This fixes problems with the Spacewalk integration in Pendulum.

Fix: proper extrinsic format and change sr25519 to ed25519

---

Cargo.lock
pallets/security/Cargo.toml
pallets/security/README.md
pallets/security/src/lib.rs
pallets/security/src/mock.rs
pallets/security/src/tests.rs
pallets/security/src/types.rs
pallets/spacewalk/Cargo.toml

This is a copy of [this pallet](https://github.com/interlay/interbtc/tree/master/crates/security/src), compilation and tests work properly. The pallet is by default included in the Spacewalk pallet under `dependencies`.

94 create security pallet

---

Cargo.lock
clients/vault/src/oracle/constants.rs
clients/vault/src/oracle/storage/impls.rs
clients/vault/src/oracle/storage/mod.rs
clients/vault/src/oracle/storage/traits.rs

request stellar archive node to download TransactionHistoryEntry
`http://history.stellar.org/prd/core-live/core_live_002/transactions/ww/xx/yy/transactions-wwxxyyzz.xdr.gz`
decode TransactionHistoryEntry
```
fn decode_xdr(xdr_data: Vec<u8>) -> XdrArchive<TransactionHistoryEntry> {
XdrArchive::<TransactionHistoryEntry>::from_xdr(xdr_data).unwrap()
}
```

Implement Transactions Archive Storage struct to retrieve missed txs + unit tests

---

pallets/nomination/src/lib.rs

Read storage after ensure signed nomination pallet
Switch reading from storage and ensuring signed.

Read storage after ensure signed in nomination pallet

---

pallets/issue/src/default_weights.rs
pallets/issue/src/lib.rs
pallets/redeem/src/default_weights.rs
pallets/redeem/src/lib.rs

update weights for issue and redeem pallet after implementation of rate limits #151

update redeem/issue weights according to rate limit functionality

---

pallets/issue/Cargo.toml
pallets/nomination/Cargo.toml
pallets/oracle/Cargo.toml
pallets/redeem/Cargo.toml
pallets/replace/Cargo.toml
pallets/security/Cargo.toml
pallets/security/src/lib.rs
pallets/vault-registry/Cargo.toml

Set `set_active_block_number` function for testing purpose unavailable for runtime

Set set_active_block_number function for testing purpose unavailable for runtime

---

clients/vault/src/metrics.rs
clients/wallet/src/horizon.rs
clients/wallet/src/lib.rs
clients/wallet/src/stellar_wallet.rs

1.  retrieve balances from  horizon stellar api
2. request stellar oracle RPC `wrapped_to_collateral` to get wrapped value in collateral currency (DOT)
3. push stellar balance (converted to DOT) to metrics(prometheus)

publish stellar balances to metrics

---

Cargo.toml
pallets/fee/Cargo.toml
pallets/issue/Cargo.toml
pallets/nomination/Cargo.toml
pallets/oracle/Cargo.toml
pallets/redeem/Cargo.toml
pallets/replace/Cargo.toml
pallets/staking/Cargo.toml
pallets/stellar-relay/Cargo.toml
pallets/vault-registry/Cargo.toml
testchain/runtime/Cargo.toml

for https://github.com/pendulum-chain/pendulum/pull/89, to avoid compile errors with the orml dependencies

update orml dependencies to v0.9.36

---

Cargo.lock
testchain/node/src/chain_spec.rs
testchain/runtime/Cargo.toml
testchain/runtime/src/lib.rs

Integrated `dia-oracle` with `spacewalk` pallets to `testchain` runtime. WORKS

Integrate dia oracle to spacewalk

---

clients/runtime/Cargo.toml
clients/runtime/src/rpc.rs
pallets/issue/src/mock.rs
pallets/nomination/src/mock.rs
pallets/oracle/src/mock.rs
pallets/redeem/src/mock.rs
pallets/replace/src/mock.rs
pallets/vault-registry/src/mock.rs
testchain/runtime/Cargo.toml
testchain/runtime/src/lib.rs

-cargo fmt --all
-add more comments
-change todo to unimplemented

testchain update configuration for oracle config

---

clients/stellar-relay-lib/src/connection/connector/message_handler.rs
clients/stellar-relay-lib/src/connection/flow_controller.rs
clients/stellar-relay-lib/src/connection/handshake.rs

Based on https://github.com/stellarbeat/js-stellar-node-connector/commit/3b032d6f545d4c421b976e970d54e0ada60d7cf9
To fix the occassional network disconnection every 2 or 3 minutes

implement pull node

---

pallets/replace/src/ext.rs
pallets/replace/src/lib.rs
pallets/replace/src/types.rs

check the amount of stellar transactions in execute_replace extrinsic

check the amount of stellar transactions in execute_replace extrinsic

---

pallets/redeem/src/lib.rs
pallets/redeem/src/tests.rs
pallets/stellar-relay/src/testing_utils.rs

fix tests with operation amount for execute_redeem extrinsic

fix tests with operation amount for execute_redeem extrinsic 

---

clients/vault/src/system.rs

6th and last item in issue [242](https://github.com/pendulum-chain/spacewalk/issues/242)

avoid storing secret key in memory

---

.github/workflows/ci-main.yml

This adds some command to free up space also to the main ci job.

Change ci-main.yml to free up space before execution

---

clients/runtime/src/integration/mod.rs
clients/runtime/src/rpc.rs
clients/runtime/src/tests.rs
pallets/fee/src/default_weights.rs
pallets/issue/src/default_weights.rs
pallets/nomination/src/default_weights.rs
pallets/oracle/src/default_weights.rs
pallets/oracle/src/dia.rs
pallets/oracle/src/lib.rs
pallets/redeem/src/default_weights.rs
pallets/replace/src/default_weights.rs
pallets/replace/src/lib.rs
pallets/stellar-relay/src/default_weights.rs
pallets/stellar-relay/src/testing_utils.rs
pallets/vault-registry/src/default_weights.rs
testchain/node/src/chain_spec.rs
testchain/node/src/command_helper.rs
testchain/runtime/src/benchmark_utils.rs
testchain/runtime/src/lib.rs

the `DiaOracleKeyConverter` for clients/runtime/src/integration/mod.rs needs to be updated @ebma

Fix clippy and type generic for dia oracle key convertor

---

pallets/stellar-relay/src/lib.rs
pallets/stellar-relay/src/tests.rs

- add validation for organization set and validator set
- update unit tests to pass unique pub key when update validator set

Add validation for organization

---

Cargo.toml
clients/runtime/src/lib.rs
clients/runtime/src/rpc.rs

Adds the necessary changes for and closes #285.

Fix client compilation for amplitude and pendulum

---

.github/workflows/ci-main.yml
.maintain/frame-weight-template.hbs
pallets/fee/src/default_weights.rs
pallets/issue/src/default_weights.rs
pallets/nomination/src/default_weights.rs
pallets/oracle/src/default_weights.rs
pallets/redeem/src/benchmarking.rs
pallets/redeem/src/default_weights.rs
pallets/replace/src/default_weights.rs
pallets/security/src/default_weights.rs
pallets/stellar-relay/src/benchmarking.rs
pallets/stellar-relay/src/default_weights.rs
pallets/vault-registry/src/default_weights.rs
primitives/src/lib.rs

This is supposed to fix the remaining clippy warnings that are dev/milestone-3 complains about. Since this is just a chore, I'll skip creating a separate issue ticket for this.

Fix clippy issues

---

pallets/stellar-relay/src/lib.rs

Updates the default genesis config of the stellar relay pallet to match the latest configuration.
Closes #373.

373 change default genesis config of stellar relay pallet

---

pallets/oracle/src/dia.rs

Add more conversions for stable coins to oracle pallet

---

Cargo.lock
clients/runner/Cargo.toml
clients/runtime/Cargo.toml
clients/runtime/client/Cargo.toml
clients/service/Cargo.toml
clients/stellar-relay-lib/Cargo.toml
clients/vault/Cargo.toml
pallets/clients-info/Cargo.toml
pallets/currency/Cargo.toml
pallets/issue/rpc/Cargo.toml
pallets/issue/rpc/runtime-api/Cargo.toml
pallets/nomination/Cargo.toml
pallets/oracle/Cargo.toml
pallets/oracle/rpc/Cargo.toml
pallets/oracle/rpc/runtime-api/Cargo.toml
pallets/redeem/rpc/Cargo.toml
pallets/redeem/rpc/runtime-api/Cargo.toml
pallets/replace/rpc/Cargo.toml
pallets/replace/rpc/runtime-api/Cargo.toml
pallets/reward-distribution/Cargo.toml
pallets/security/Cargo.toml
pallets/vault-registry/Cargo.toml
pallets/vault-registry/rpc/Cargo.toml
pallets/vault-registry/rpc/runtime-api/Cargo.toml
primitives/Cargo.toml
rpc/Cargo.toml
testchain/node/Cargo.toml
testchain/runtime/Cargo.toml

Set versions in all crates to `1.0.0`

---

clients/stellar-relay-lib/resources/config/mainnet/stellar_relay_config_mainnet_iowa.json
clients/stellar-relay-lib/src/config.rs
clients/stellar-relay-lib/src/connection/connector/connector.rs
clients/stellar-relay-lib/src/connection/hmac.rs
clients/stellar-relay-lib/src/connection/overlay_connection.rs
clients/vault/src/oracle/collector/collector.rs
clients/vault/src/oracle/collector/proof_builder.rs
clients/vault/src/oracle/types/constants.rs

427 fix proof building issue from archives on mainnet

---

clients/runner/src/runner.rs

Fix runner test

---

.github/workflows/build.yml

The workflow was triggering the wrong pipeline.

Change `project_id` of build.yml workflow

---

clients/vault/src/oracle/types/constants.rs

Tested it locally, works like a charm. 
Closes #463.

Change `MAX_SLOTS_TO_REMEMBER` parameter

---

primitives/src/lib.rs

- Change camelCasing on CurrencyId types

Fix vault client not able to connect due to type mismatch
