pendulum-chain/spacewalk

- README.md
Adds some information about how issuing and redeeming works in Spacewalk. The description is still on a higher level but I think it is enough to understand what is going on in the code. 
If you think it should go more in-depth, I can also add more details.
Closes #32.
> Add documentation about Issue and Redeem to README

- README.md
Removes duplicate sections from the README. I must have somehow pasted it twice by mistake.
> Remove duplicate docs from README

- clients/Cargo.lock
- clients/README.md
- clients/runtime/Cargo.toml
- clients/runtime/src/lib.rs
- clients/runtime/src/types.rs
- clients/vault/Cargo.toml
Removes the usages of `spacewalk-runtime` in the vault client and adds a new `multi-address` cargo feature which can be supplied (and should be used when compiling spacewalk for pendulum). 
Although this might still not cover all possible type configurations (since there are only two options for now), I would opt for keeping it simple for now and extending it only once we need to. The different types for account Id and address are based on what interbtc has configured for their chain, and what we need for pendulum.
Closes #71.
> Make clients independent of test chain

- .github/workflows/ci.yml
Adds caches for the CI jobs. The `rust-cache` action caches the dependencies, speeding up their download time if the Cargo.lock file did not change. 'sccache' is used to save the compiled artifacts and thus speed up compilation times. 
Clippy [does not work with sccache](https://github.com/rust-lang/rust-clippy/issues/3840) however, so I had to remove it. IMO it should be fine to remove it because it just spits out some warnings, that we probably ignore most of the time anyway.
These changes can cut down the duration of CI runs from ~30 minutes to ~12 minutes. At least for subsequent runs, where the dependencies did not change but just the code.
It also adds the `--all-features` flag to cargo test, because it is needed for the vault tests (as we have to specify either parachain-metadata, …
> Use cache in github ci workflow

- pallets/currency/src/mock.rs
- pallets/fee/src/mock.rs
- pallets/fee/src/tests.rs
- pallets/issue/src/benchmarking.rs
- pallets/issue/src/lib.rs
- pallets/issue/src/mock.rs
- pallets/issue/src/tests.rs
- pallets/nomination/src/mock.rs
- pallets/oracle/src/mock.rs
- pallets/oracle/src/tests.rs
- pallets/redeem/src/benchmarking.rs
- pallets/redeem/src/lib.rs
- pallets/redeem/src/mock.rs
- pallets/redeem/src/tests.rs
- pallets/replace/src/mock.rs
- pallets/reward/src/mock.rs
- pallets/security/src/mock.rs
- pallets/staking/src/mock.rs
- pallets/stellar-relay/src/mock.rs
- pallets/stellar-relay/src/tests.rs
- pallets/vault-registry/src/mock.rs
- pallets/vault-registry/src/tests.rs
This PR fixes the type issues that arise because the mocks and tests were not updated accordingly when upgrading to v0.9.31 (which I, unfortunately, forgot to add to the last PR because I did not run the tests).
It also removes the `asset` parameter from the `request_{issue/redeem}()` extrinsics which was not used anyways. I originally added it because I thought we would need it eventually.
> Remove asset from request extrinsics

- clients/stellar-relay/src/connection/services.rs
"peeking empty" happens when we connect to node with incorrect overlay_version:
there is new version that works good without "peeking empty" error: 
`let node_info = NodeInfo::new(19, 25, 23, "v19.5.0".to_string(), network);`
this is the old one that we stuck forever with "peeking empty" error:
`let node_info = NodeInfo::new(19, 21, 19, "v19.1.0".to_string(), network);`
There is no chance that we we will receive any message once we go to this case statement. 
```
Ok(Ok(0)) => {
log::error!("peeking empty");
}
```
introduce retry_read variable. increment each time received zero size
Closing https://github.com/pendulum-chain/spacewalk/issues/120
> Drop connection after the defined retries and timeouts.  Closing issue #120

- Cargo.lock
- clients/runtime/src/integration/mod.rs
- clients/runtime/src/lib.rs
- clients/runtime/src/rpc.rs
- clients/runtime/src/types.rs
- clients/service/src/lib.rs
- clients/vault/Cargo.toml
- clients/vault/src/execution.rs
- clients/vault/src/issue.rs
- clients/vault/src/lib.rs
- clients/vault/src/metrics.rs
- clients/vault/src/oracle/handler.rs
- clients/vault/src/oracle/mod.rs
- clients/vault/src/redeem.rs
- clients/vault/src/replace.rs
- clients/vault/src/system.rs
- clients/vault/tests/vault_integration_tests.rs
- clients/wallet/Cargo.toml
- clients/wallet/src/error.rs
- clients/wallet/src/horizon.rs
- clients/wallet/src/lib.rs
- clients/wallet/src/stellar_wallet.rs
- primitives/src/lib.rs
Adds the handling for redeem and replace events to the vault client.
Also adds the last missing integration tests.
The `send_payment_to_address()` function of the StellarWallet struct now requires a mutable reference to `self` because it now uses and sets a local account sequence number. This number is necessary because, when calling this function multiple times before a ledger close, all transactions would be created with the same sequence number, meaning that only one of them can go through and the others are rejected by the stellar network. Keeping a local copy of this sequence number mitigates this problem because we can increase it for every new transaction call.
> Add handling for redeem/replace events to vault

- clients/vault/src/execution.rs
- clients/vault/src/issue.rs
- clients/vault/src/oracle/collector/collector.rs
- clients/vault/src/oracle/collector/handler.rs
- clients/vault/src/oracle/collector/proof_builder.rs
This changes the level of the `tracing` statements in the oracle agent to debug. IMO they are irrelevant for the regular user of the vault client.
> Change level of some log statements

- pallets/oracle/src/lib.rs
- add `DataProvider` to oracle pallet config
- Add new Storage `Vec<OracleKeys>`
- Add new extrinsic to update the Storage with `oracle_keys`
- load prices `on_initialize` to track the price status and move parachain offline or online
- remove unused `Storages`
> Use DataProvider type in oracle from Pallet config

- Cargo.lock
- pallets/issue/Cargo.toml
- pallets/issue/src/mock.rs
- pallets/issue/src/tests.rs
- pallets/oracle/src/benchmarking.rs
- pallets/oracle/src/lib.rs
- pallets/oracle/src/mock.rs
- pallets/oracle/src/oracle_mock.rs
- finish oracle pallet to be compatible with other spacewalk pallets
- create oracle_mock rs file in oracle pallet to introduce easy way mock oracle pallet in test runtime in other pallets.
- issue pallet tests passed successfully
> Compatibility done! Oracle pallet + issue pallets works fine

- Cargo.lock
- pallets/fee/Cargo.toml
- pallets/issue/Cargo.toml
- pallets/issue/src/benchmarking.rs
- pallets/issue/src/mock.rs
- pallets/issue/src/tests.rs
- pallets/nomination/src/benchmarking.rs
- pallets/nomination/src/mock.rs
- pallets/oracle/src/benchmarking.rs
- pallets/oracle/src/dia.rs
- pallets/oracle/src/lib.rs
- pallets/oracle/src/mock.rs
- pallets/oracle/src/oracle_mock.rs
- pallets/oracle/src/tests.rs
- pallets/redeem/src/benchmarking.rs
- pallets/redeem/src/mock.rs
- pallets/replace/src/benchmarking.rs
- pallets/replace/src/mock.rs
- pallets/vault-registry/src/benchmarking.rs
- pallets/vault-registry/src/mock.rs
- testchain/node/src/chain_spec.rs
- testchain/runtime/Cargo.toml
- testchain/runtime/src/lib.rs
- introduce new type in oracle config `DataFeedProvider` because all tests and benchmarks across all spacewalk pallets use `_feed_values` function  and `_set_exchange_rate` 
- add `static COINS: RwLock<Vec<Data>> = RwLock::new(vec![]);` for mock runtime to store prices in `DataFeedProvider`
- Mock Test runtime with `MockDiaOracle`
- `impl Convert<OracleKey, Option<(Vec<u8>, Vec<u8>)>> for MockDiaOracleConvertor`
- `impl Convert<(Vec<u8>, Vec<u8>), Option<OracleKey>> for MockDiaOracleConvertor`
-  still need refactoring.
> Prepare spacewalk oracle for DIA integration.

- pallets/issue/src/mock.rs
- pallets/nomination/src/mock.rs
- pallets/oracle/src/lib.rs
- pallets/oracle/src/mock.rs
- pallets/oracle/src/oracle_mock.rs
- pallets/redeem/src/mock.rs
- pallets/replace/src/mock.rs
- pallets/vault-registry/src/mock.rs
- testchain/runtime/Cargo.toml
- testchain/runtime/src/lib.rs
- solve issue with `thead_local` in tests. When mock `DataFeeder` and `DataProviderExtended`
- solve issue for `spacewalk-testchain-runtime` with additional config type `DataFeeder`
- cargo` test --all --all-features`  build and passed. only one tests failed : `test_subxt_processing_events_after_dispatch_error`
> Spacewalk oracle refactoring

- clients/runtime/src/tests.rs
- `cargo test --all --all-features` passed successfully
> Remove integration tests related to oracle feed_values extrinsic

- clients/runtime/src/integration/mod.rs
- clients/runtime/src/rpc.rs
- clients/runtime/src/tests.rs
- clients/stellar-relay-lib/src/tests/mod.rs
- pallets/oracle/src/lib.rs
- pallets/oracle/src/oracle_mock.rs
- pallets/redeem/src/mock.rs
- primitives/src/lib.rs
- testchain/node/src/chain_spec.rs
- testchain/runtime/src/lib.rs
- reimplement `OraclePallet` trait for `SpacewalkParachain` in subxt client
- now `feed_values` Oracle pallet send request to `DIA` oracle pallet
- `cargo test --all --all-features` successfully passed
- update chain_spec to specify `authorized_oracles` for DIA oracle and specify OracleKeys vector for spacewalk pallet.
- reimplement `ConvertPrice` and `ConvertMoment` struct for testchain
> update rpc client to submit and query oracle data via Dia-Oracle

- clients/runtime/src/integration/mod.rs
- clients/runtime/src/rpc.rs
- clients/vault/tests/vault_integration_tests.rs
- pallets/oracle/src/lib.rs
Solved the actual problem with vault integration tests.
By some reason `timestamp storage` return **0** and therefore `spacewalk pallets`
go to offline status because not all `OracleKeys` has prices during
begin_block function in oracle spacewalk.
> Oracle pallet begin block improve parachain status

- pallets/issue/src/mock.rs
- pallets/nomination/src/mock.rs
- pallets/oracle/src/mock.rs
- pallets/oracle/src/oracle_mock.rs
- pallets/oracle/src/tests.rs
- pallets/redeem/src/mock.rs
- pallets/replace/src/mock.rs
- pallets/vault-registry/src/mock.rs
Some unit tests foes not work because mock `thead_local` variable contains `Vec` of prices instead of `HashMap`
and therefore after updates price get function take the first(old) element in vector instead of a new value(last value in vector).
> fix unit tests using hash map instead of vector

- primitives/src/lib.rs
- primitives/src/tests.rs
This is item #5 of [#242](https://github.com/pendulum-chain/spacewalk/issues/242)
if conversion rate is too big for i64, set it to what its max is.
if the i64 value reaches negative, make it zero for u128.
^ Unless that's the wrong approach?
> 242 - unsafe integer cast for `BalanceConversion`'s `StaticLookUp` implementation

- .github/workflows/ci-dev.yml
- clients/runtime/src/rpc.rs
- clients/vault/tests/vault_integration_tests.rs
- pallets/oracle/src/oracle_mock.rs
This PR fixes the currently failing integration tests. They were broken because of the faulty timestamp that we passed in the `feed_values` function of the integration tests.
I also decided to change the exchange rates of the assets we set for the integration tests. This is not necessary but I decided to change them to make them more 'realistic'.
> Fix integration tests

- clients/vault/src/system.rs
- clients/wallet/src/error.rs
This change is necessary to fix the vaults cloud deployment.
Closes #301.
> 301 trim stellar secret key before using it in vault client

- clients/runtime/src/rpc.rs
- clients/vault/tests/vault_integration_tests.rs
- pallets/oracle/rpc/runtime-api/src/lib.rs
- pallets/oracle/rpc/src/lib.rs
- pallets/oracle/src/lib.rs
- pallets/oracle/src/tests.rs
- pallets/vault-registry/src/benchmarking.rs
- pallets/vault-registry/src/tests.rs
PR related to issue #321 
renamed functions:
- wrapped_to_collateral -> currency_to_usd
- collateral_to_wrapped -> usd_to_currency
change the order of calls functions in oracle convert function:
new order is 
```
let base = Self::currency_to_usd(amount.amount(), amount.currency())?;
Self::usd_to_currency(base, currency_id)?
```
> Change naming of oracle pallet functions

- clients/runtime/src/integration/mod.rs
- clients/vault/src/replace.rs
- clients/vault/tests/vault_integration_tests.rs
- update integration tests for vault. pass `wrapped_currency_id` from vault data.
- updated `get_required_vault_collateral_for_issue` with one more parameter `wrapped_currency` to pass it into `get_required_collateral_for_wrapped`
> update vault integration tests

- clients/runtime/src/rpc.rs
- pallets/vault-registry/rpc/runtime-api/src/lib.rs
- testchain/node/src/chain_spec.rs
- testchain/runtime/src/lib.rs
- move definition of `WRAPPED_CURRENCY_ID` from runtime to `chain_spec`
- use `wrapped_currency_id` parameter instead of hardcoded value `GetWrappedCurrencyId::get()` in runtime.
- rename `collateral_currency` to `collateral_currency_id`
> Move WRAPPED_CURRENCY_ID from runtime to chain_spec and remove usage of GetWrappedCurrencyId::get()

- clients/runtime/src/integration/mod.rs
- clients/runtime/src/rpc.rs
- clients/vault/src/replace.rs
- clients/vault/tests/vault_integration_tests.rs
- pallets/vault-registry/rpc/runtime-api/src/lib.rs
- pallets/vault-registry/rpc/src/lib.rs
- testchain/node/src/chain_spec.rs
- testchain/runtime/src/lib.rs
- updated get_required_collateral_for_wrapped RPC function in vault-registry
- updated testchain runtime. `wrapped_currency_id` in testchain does not passed to the pallet function. use default value as  `GetWrappedCurrencyId::get()`
```
const WRAPPED_CURRENCY_ID: CurrencyId = CurrencyId::AlphaNum4(
*b"USDC",
[
20, 209, 150, 49, 176, 55, 23, 217, 171, 154, 54, 110, 16, 50, 30, 226, 102, 231, 46, 199,
108, 171, 97, 144, 240, 161, 51, 109, 72, 34, 159, 139,
],
);
```
> Update signature of get_required_collateral_for_wrapped RPC function

- clients/vault/src/execution.rs
- clients/vault/src/metrics.rs
Amends the changes for #160.
We forgot to add a function that keeps the Stellar balance metric up-to-date. This PR changes it such that the Stellar balance metrics are updated periodically or after executing a request.
> 160 amend metrics reporting

- primitives/src/lib.rs
PR related to this issue https://github.com/pendulum-chain/spacewalk/issues/331
- first widen the Stellar amount to u128 
- multiply with 100_000.
> Add safer amount conversion from Stellar amounts to host chain amounts

- .github/workflows/build.yml
Adds a workflow file that automatically triggers an action to build the binaries for spacewalk.
Related to [this](https://github.com/pendulum-chain/tasks/issues/28) task.
> Add flow for automatically building binaries

- testchain/runtime/src/lib.rs
PR related to issue https://github.com/pendulum-chain/spacewalk/issues/325
- updated testchain runtime
- use different implementation of `XCMCurrencyConversion` trait depends on enabled feature flag.
- add new implementation for non `testing-utils` feature in spacewalk testnet
- keep the prev implementation of `XCMCurrencyConversion` trait for `SpacewalkNativeCurrencyKey` to keep integration working as expected.
> Use different XCMCurrencyConversion impl depends on features flag

- pallets/issue/src/lib.rs
This changes the `execute_issue()` extrinsic to not charge a fee upon successful execution. 
The `execute_redeem()` function was not changed because it actually already implements this fee waiving mechanism. 
Closes #348.
> Waive fee for successful execution of `execute_issue()` extrinsic

- clients/vault/src/replace.rs
- clients/vault/src/system.rs
- pallets/stellar-relay/src/lib.rs
- pallets/stellar-relay/src/validation.rs
continuation of https://github.com/pendulum-chain/spacewalk/pull/385. Please review the base PR before continuing with this.
* ## 9B2-04 | Logic Should be Moved To an Separate Function - Refactoring (partial)
* ## **from audit:**
* Refactoring is recommended in the function `validate_stellar_transaction()` from stellar_relay/lib.rs.
* `run_service()` from vault/src/system.rs
* ## new file
* validation.rs (covers the logic of `validate_stellar_transaction()`
> 257 FIx Informational Issues - Logic Should be Moved To an Separate Function - Refactoring

- clients/runtime/src/error.rs
- clients/runtime/src/rpc.rs
- clients/vault/src/error.rs
- clients/vault/src/issue.rs
- clients/vault/src/oracle/agent.rs
- clients/vault/src/oracle/collector/proof_builder.rs
- clients/vault/src/oracle/storage/impls.rs
- clients/vault/src/system.rs
- clients/wallet/src/error.rs
- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/horizon/responses.rs
- clients/wallet/src/horizon/tests.rs
- clients/wallet/src/horizon/traits.rs
- clients/wallet/src/stellar_wallet.rs
- pallets/issue/src/lib.rs
- pallets/oracle/src/lib.rs
- pallets/redeem/src/lib.rs
- pallets/redeem/src/tests.rs
continues from #385.
~~This should be merged to branch [257-fix-informational-issues](https://github.com/pendulum-chain/spacewalk/tree/257-fix-informational-issues) AFTER  https://github.com/pendulum-chain/spacewalk/pull/388 , since system.rs contains a lot of changes.~~
* ## IMP-01 Same Behavior Defined for different conditions
* ### **from audit:**
* The function create_filename_and_data() from clients/vault/src/oracle/storage/impls.rs has two different if statements inside the for loop that iterates through the Envelopes Map.
* The if statements handle different cases but their bodies are equal. This means that either one of the statements is missing some change or that in reality, there shouldn't be two different scenarios.
* ### **files covered:**
* …
> 257 Fix informational issues part 3

- clients/runtime/src/rpc.rs
- clients/vault/src/cancellation.rs
- clients/vault/src/execution.rs
- clients/vault/src/metrics.rs
- clients/vault/src/oracle/collector/proof_builder.rs
- clients/vault/src/replace.rs
- clients/vault/src/system.rs
- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/horizon/traits.rs
- pallets/issue/src/lib.rs
- pallets/vault-registry/src/lib.rs
- primitives/src/lib.rs
Some notable mentions:
- LIY-04/LIT-05 was already solved since audit.
- LIV-01 "Duplicated Helper Function Call" -> I left this unchanged. In my opinion cannot be optimized without modifying (splitting) `try_deposit_collateral` from pallet vault-registry. Although in `deposit_collateral` extrinsic it is duplicated the active vault check, this function is used also externally outside the pallet.
- IMP-02 "Empty Strings as prefixes" -> I also left this unchanged. I believe this could be useful in the future, since it is already coded and works, for extension purposes.
- HOR-01/HOI-01 Unnecessary Variable cloning -> the code seems to have changed since then. Couldn't find that specific reference.
- EXC-02/EXU-03 Double filter() calls can be reduced with filter_map() -> Is addressed along …
> 263 add optimizations audit recommendations

- clients/runner/src/runner.rs
> 421 fix failing runner test

- clients/stellar-relay-lib/examples/connect.rs
- clients/stellar-relay-lib/src/connection/connector/message_creation.rs
- clients/stellar-relay-lib/src/connection/connector/message_handler.rs
- clients/stellar-relay-lib/src/connection/error.rs
- clients/stellar-relay-lib/src/connection/helper.rs
- clients/stellar-relay-lib/src/connection/overlay_connection.rs
- clients/stellar-relay-lib/src/connection/services.rs
- clients/vault/src/oracle/agent.rs
- clients/vault/src/oracle/collector/proof_builder.rs
- clients/vault/tests/vault_integration_tests.rs
- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/horizon/traits.rs
- clients/wallet/src/stellar_wallet.rs
- pallets/replace/src/lib.rs
- primitives/src/lib.rs
Reconnection:
There are 2 threads that run independently (found in service.rs)
* `fn connection_handler()` - handles action from the connection
* `fn receiving_service()` - handles messages from the server
If connection fails, both should stop running.
In the case of an Error Message received, reconnection is required. 
example: **` Error{ code:ErrConf message:already-connected peer: `**:
* `fn connection_handler()` - relays the error message and return (which stops the thread)
* `fn receiving_service()` - no more data found in the read stream  and return (which stops the thread)
The error message is relayed inside `fn listen()` (found in agent.rs) and it goes through the "reconnect logic".
> Make vault client retry connection to overlay connection when handshake fails

- clients/vault/tests/vault_integration_tests.rs
Maybe the `sleep` statement is the problem, but not 100% sure.
I ran the `test_cancel_scheduler_succeeds()` locally 10 times and it passed for each of them. Let's see if it also works in the CI job by running it a couple of times. 
The CI job passed 4 out of 5 times and the one time it failed was with a different error (unrelated to this problem).
Closes #386.
> Fix occasional consensus error

- .github/workflows/build.yml
This fixes issues with the Gitlab pipeline not being called properly.
> Add the `ref: development` parameter to the build.yml file

- clients/vault/tests/helper/helper.rs
- clients/vault/tests/vault_integration_tests.rs
closes #313 
Created a loop for `send_payment_to_address` to keep resending the same transaction, should the error be `tx_bad_seq` error. 
This is _only_ for integration tests.
> 313 - retry integration tests for `tx_bad_seq` errors

- Cargo.lock
- clients/vault/src/replace.rs
- clients/vault/src/system.rs
- clients/vault/tests/helper/helper.rs
- clients/vault/tests/vault_integration_tests.rs
- clients/wallet/Cargo.toml
- clients/wallet/src/cache.rs
- clients/wallet/src/error.rs
- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/horizon/responses.rs
- clients/wallet/src/horizon/tests.rs
- clients/wallet/src/lib.rs
- clients/wallet/src/mock.rs
- clients/wallet/src/operations.rs
- clients/wallet/src/resubmissions.rs
- clients/wallet/src/stellar_wallet.rs
- primitives/src/lib.rs
The aim of this PR is to add error handling logic for failed submissions.
Closes #340
1. A few method renames;
1. Introduce new file: `resubmissions.rs`, dedicated for resubmission and handling of errors. Bulk of the code is here
2. Introduced new file: `mock.rs`, contains the function helpers for the tests cases
3. ~Also updated the `resubmit_transactions_from_cache()`, with a parameter that helps handle failed tasks~
* clients/wallet/src/resubmissions.rs
* ~type `FailedTasks` = essential for removing transaction envelopes in cache for failed resubmissions~
* :star: instead of complicating things with channels, I just immediately call the `remove_tx_envelope_from_cache()` if the error is not viable for resubmission
* fn `resubmit_transactions_from_cache()` = the only public method. Every …
> [WIP] 340 add handling for non recoverable stellar submission errors

- pallets/stellar-relay/src/tests.rs
- pallets/stellar-relay/src/validation.rs
Changes the validation logic so that not each organization has to meet the requirement of >1/2 validators but only >2/3 of the total organizations have to meet it. This aligns to the discussion in [this](https://www.notion.so/satoshipay/23-11-29-Stellar-relay-consensus-issues-d587d75c4616429eb8c4a134dd54ece2) notion page.
Closes #457.
> Change requirement for validators to build valid quorum set

- clients/runtime/src/error.rs
- clients/runtime/src/lib.rs
- clients/runtime/src/rpc.rs
- clients/runtime/src/tests.rs
- clients/vault/src/requests/execution.rs
- clients/vault/src/requests/structs.rs
- clients/vault/src/system.rs
Closes #452 
- Uses the string `data` filed on the parsed error to detect recoverable errors (lack of funds, incorrect nonce).
- Otherwise, the service will avoid retry of the same call, since it is impossible to obtain a different result without modifying it (except vault operator's input).
- A new condition is added so that if the error is of type `POOL_UNACTIONABLE` or `POOL_UNKNOWN_VALIDITY` (which are not necessarily invalid transactions) the vault will retry the transaction.
- If the service fails to start it will send a [shutdown signal](https://github.com/pendulum-chain/spacewalk/compare/452-vault-client-retries-transaction-submission-for-unrecoverable-errors?expand=1#diff-0f76594421d4493b3bba1c9ed7864cdab7148f19c5d3a18a9bcc9a174bb85aa8R286) to avoid waiting a dead process.
> 452 vault client retries transaction submission for unrecoverable errors

- clients/vault/src/oracle/agent.rs
- clients/vault/src/oracle/collector/proof_builder.rs
- clients/vault/src/oracle/testing_utils.rs
Fixes some tests. The test to get the current proof was changed to use a random keypair so that we could rule out issues with the client already being connected to the overlay node, thus encountering a timeout in that test.
> release: Fix bug in test and retry release 1.0.3

- .chglog/CHANGELOG.tpl.md
- .chglog/config.yml
This template can be used to create a changelog. Its main purpose is to be used in Spacewalk's release flow to automatically generate a description for the new releases. 
To generate the changelog you need to install git-chglog, see [here](https://github.com/git-chglog/git-chglog?tab=readme-ov-file#installation) and then run `git-chglog -o CHANGELOG.md`.
The CI job will run the generation with the latest tag as the argument so that the changelog is only generated containing the changes for the latest release. For example to generate the release notes for release `v1.0.3`, it will use `git-chglog -o CHANGELOG.md v1.0.3..`.
Closes #434.
> 434 add configuration for automatic changelog generation

- clients/wallet/src/horizon/tests.rs
Changes the hardcoded reference to a claimable balance on Stellar mainnet instead of testnet so that this issue doesn't appear for the next reset. I issued this claimable balance entry from one of our accounts so we don't have a risk of someone claiming this entry in the meantime.
Closes #469.
> Fix failing test after Stellar testnet reset

- clients/vault/src/metrics.rs
A display label is added of the form `{collateral}_{wrapped}`
Where both collateral and wrapped are formatted for display the following way:
```
XCM = "XCM(value)",
StellarNative = "XLM"
Native = "Native"
Stellar::AlphaNum4 {code, ..} | AlphaNum12 {code, ..} = "code"
CurrencyId::ZenlinkLPToken(token1_id, token1_type, token2_id, token2_type) = "LP_{}_{}_{}_{}", token1_id, token1_type, token2_id, token2_type)
```
Also appends status or type of the corresponding metric so that display name is formatted as 
```
"{collateral}_{wrapped} - {status/type}"
```
> 368 improve exported metrics for usage in grafana dashboards

- pallets/clients-info/Cargo.toml
- pallets/currency/Cargo.toml
- pallets/fee/Cargo.toml
- pallets/issue/Cargo.toml
- pallets/nomination/Cargo.toml
- pallets/oracle/Cargo.toml
- pallets/pooled-rewards/Cargo.toml
- pallets/redeem/Cargo.toml
- pallets/replace/Cargo.toml
- pallets/reward-distribution/Cargo.toml
- pallets/reward/Cargo.toml
- pallets/security/Cargo.toml
- pallets/staking/Cargo.toml
- pallets/vault-registry/Cargo.toml
This PR adds the `try-runtime` features to some of the pallets such that we can compile the runtime with this feature enabled.
This is related to [tasks/#64](https://github.com/pendulum-chain/tasks/issues/64), but overall we require this so we can tests future runtime upgrades or other tests with `try-runtime`.
> add-try-runtime-feature

- Cargo.lock
- clients/vault/src/requests/structs.rs
- clients/vault/tests/helper/helper.rs
- clients/vault/tests/vault_integration_tests.rs
- clients/wallet/Cargo.toml
- clients/wallet/src/error.rs
- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/horizon/responses.rs
- clients/wallet/src/horizon/serde.rs
- clients/wallet/src/horizon/tests.rs
- clients/wallet/src/horizon/traits.rs
- clients/wallet/src/mock.rs
- clients/wallet/src/resubmissions.rs
- clients/wallet/src/stellar_wallet.rs
- clients/wallet/src/types.rs
closes #312 
1. **Remove** _`DEFAULT_STROOP_FEE_PER_OPERATION`_ constant in production code.
2. **Remove** _`stroop_fee_per_operation`_ parameters on method **`fn send_to_address()`**; since
3. fee will be queried from horizon; the method is called`fn get_fee_stats()`
4. Memoization using the [cached](https://docs.rs/cached/0.47.0/cached/) lib to return the same result until 10 minutes (or 600 seconds) have elapsed.
~~todo: only memoize for `Ok()` results.~~
----  
1. `clients/wallet/src/types.rs` -> has the `FeeAttribute` enum, where you can pick which one to base the operation on
2. `clients/wallet/src/horizon/responses.rs` -> Defining the response into a struct of `FeeStats` and `FeeDistribution`
3. `clients/wallet/src/horizon/serde.rs` -> Implements deserialization of the fields in …
> 312 use stellar fee statistics to derive transaction fee

- clients/stellar-relay-lib/resources/config/mainnet/stellar_relay_config_mainnet_iowa.json
- clients/stellar-relay-lib/resources/config/testnet/stellar_relay_config_sdftest1.json
- clients/stellar-relay-lib/resources/config/testnet/stellar_relay_config_sdftest2.json
- clients/stellar-relay-lib/resources/config/testnet/stellar_relay_config_sdftest3.json
- clients/stellar-relay-lib/src/tests/mod.rs
- clients/vault/resources/config/mainnet/stellar_relay_config_frankfurt.json
- clients/vault/resources/config/mainnet/stellar_relay_config_iowa.json
- clients/vault/resources/config/mainnet/stellar_relay_config_singapore.json
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest1.json
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest2.json
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest3.json
- clients/wallet/src/horizon/tests.rs
This PR adds changes that fix failing unit tests. The overlay configuration files were updated and a different secret key is used for testnet. 
Closes #476.
> 476 update stellar overlay configuration files

- Cargo.lock
- clients/stellar-relay-lib/Cargo.toml
- clients/stellar-relay-lib/examples/connect.rs
- clients/stellar-relay-lib/src/connection/connector/connector.rs
- clients/stellar-relay-lib/src/connection/connector/message_handler.rs
- clients/stellar-relay-lib/src/connection/connector/message_reader.rs
- clients/stellar-relay-lib/src/connection/connector/message_sender.rs
- clients/stellar-relay-lib/src/connection/error.rs
- clients/stellar-relay-lib/src/connection/helper.rs
- clients/stellar-relay-lib/src/overlay.rs
- clients/stellar-relay-lib/src/tests/mod.rs
- clients/vault/Cargo.toml
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest1.json
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest2.json
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest3.json
- clients/vault/src/oracle/agent.rs
- clients/vault/src/oracle/collector/collector.rs
- clients/vault/src/oracle/storage/impls.rs
- clients/vault/src/oracle/testing_utils.rs
- clients/vault/tests/helper/mod.rs
Somehow in **_K8s_**, Tokio's [TcpStream](https://github.com/tokio-rs/tokio/blob/1b1b9dc7e388d0619fe7bfe6a7618fff596fdee1/tokio/src/net/tcp/stream.rs#L69-L72) is stuck at "write ready" and is never "read ready". 
Even after connecting using Rust's [Tcpstream](https://doc.rust-lang.org/src/std/net/tcp.rs.html#156-158) and then converting it to [Tokio's](https://github.com/tokio-rs/tokio/blob/1b1b9dc7e388d0619fe7bfe6a7618fff596fdee1/tokio/src/net/tcp/stream.rs#L202-L206), the stream _never_ changes to "read ready".
That's when I decided to use ~Rust's [Tcpstream](https://doc.rust-lang.org/std/net/struct.TcpStream.html) completely.~ [`async-std` library](https://github.com/async-rs/async-std).
In terms of code changes, these are the difference you will see:
| Tokio | Async-Std | ~Rust Std~ | …
> Replacing Tokio's `TcpStream` with `async-std` `TcpStream`

- clients/runtime/Cargo.toml
- clients/runtime/src/cli.rs
- clients/service/src/cli.rs
- clients/stellar-relay-lib/resources/config/testnet/stellar_relay_config_sdftest1.json
- clients/stellar-relay-lib/resources/config/testnet/stellar_relay_config_sdftest2.json
- clients/stellar-relay-lib/resources/config/testnet/stellar_relay_config_sdftest3.json
- clients/vault/Cargo.toml
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest1.json
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest2.json
- clients/vault/resources/config/testnet/stellar_relay_config_sdftest3.json
- clients/vault/src/oracle/agent.rs
- clients/vault/src/system.rs
closes #431 
adding the ff. arguments an ENV option:
1. KEYRING
2. KEYFILE
3. KEYNAME
4. SPACEWALK_PARACHAIN_URL
5. STELLAR_VAULT_SECRET_KEY_FILEPATH
6. STELLAR_OVERLAY_CONFIG_FILEPATH
7. AUTO_REGISTER
note for **_AUTO_REGISTER_**:  since the value must be a tuple, make sure to **_enclose it with double quotes_**. 
:no_good: :x: `export AUTO_REGISTER=0,GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN:USDC,1000000` :x: :no_good:
:white_check_mark: :ok_hand: **`export AUTO_REGISTER="0,GAKNDFRRWA3RPWNLTI3G4EBSD3RGNZZOY5WKWYMQ6CQTG3KIEKPYWAYC:USDC,1000000"`** :ok_hand: :white_check_mark:
For arguments that accept _`option`_,  make sure to **_enclose it with double quotes_** with the _ACTUAL_ value.
:no_good: :x: `export MAX_NOTIFS_PER_SUBSCRIPTION="1"` :x: :no_good:
:no_good: :x: …
> 431 Add environment variable options to Spacewalk

- .github/workflows/ci-main.yml
- Cargo.lock
- clients/runtime/Cargo.toml
- clients/vault/Cargo.toml
- clients/vault/src/oracle/agent.rs
- clients/vault/tests/vault_integration_tests.rs
- clients/wallet/src/error.rs
- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/horizon/responses.rs
- clients/wallet/src/horizon/serde.rs
- clients/wallet/src/horizon/tests.rs
- clients/wallet/src/horizon/traits.rs
- clients/wallet/src/resubmissions.rs
- clients/wallet/src/stellar_wallet.rs
Closes #494.
The multiple mainnet integration issues (and its fixes) are as follows:
* cannot determine which `DecimalsLookUp` to use. 
* fix: make sure for the feature `integration-test`, the clients/vault uses the `standalone-metadata` feature:
https://github.com/pendulum-chain/spacewalk/blob/ea913fab5ae2a47368d48206fba5e7897e3c118d/clients/vault/src/lib.rs#L52-L53
* fix: make sure the clients/runtime has access to the [mainnet-runtime](https://github.com/pendulum-chain/spacewalk/tree/main/testchain/runtime/mainnet)
* failed with
```
HorizonResponseError(reqwest::Error { kind: Decode, source: Error("invalid type: string \"ySHX => SHX/XLM DAILY\", expected a borrowed string", line: 9484, column: 44) })
```
* fix: Some memo texts have non-literal characters, messing up deserialization.  A …
> Improve robustness of Spacewalk integration tests

- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/horizon/responses.rs
- clients/wallet/src/resubmissions.rs
- pallets/oracle/rpc/runtime-api/src/lib.rs
- testchain/node/src/service.rs
This PR adds handling for 'tx_insufficient_fee' errors. 
We create a new transaction with a fee that is 10 times higher than the previous one. This 10x factor is adopted from the requirement of FeeBump transactions, see [here](https://developers.stellar.org/docs/learn/encyclopedia/fees-surge-pricing-fee-strategies#fee-bumps-on-past-transactions). We **cannot** use fee bump transactions however, as we did not add proper handling for them in the stellar-relay pallet [here](https://github.com/pendulum-chain/spacewalk/blob/bda384bcc6db3da88198c714851a261dcdea1063/pallets/currency/src/lib.rs#L135). Using fee bump transactions here is not necessary though as they were introduced with a different purpose in mind. For more information see …
> 499 make vault retry stellar transaction submission for tx insufficient fee error

- clients/vault/src/oracle/collector/proof_builder.rs
- clients/vault/src/oracle/storage/traits.rs
> 514 Remove archive files after use

- clients/runtime/src/error.rs
- clients/runtime/src/rpc.rs
- clients/vault/src/oracle/storage/traits.rs
- clients/vault/src/requests/structs.rs
Closes #516.
Upon receiving a `RequestTimeout` error, the client should retry sending the transaction. This will be done with the [same](https://github.com/pendulum-chain/spacewalk/blob/9aafee4a22877ad2cb7c6c515b3b505002bd41e5/clients/runtime/src/retry.rs#L43) `backoff` used for other errors defined as "Skippable". 
We add a [method](https://github.com/pendulum-chain/spacewalk/pull/518/files#diff-6469b7c5aed83b33ec6bbd2a61154190361c333995a98a3c172436491a901b9bR204) to identify the `RequestTimeout` error, and add it to the respective closures with the corresponding `Skip` retry policy.
The client's [existing](https://github.com/pendulum-chain/spacewalk/blob/9aafee4a22877ad2cb7c6c515b3b505002bd41e5/clients/runtime/src/rpc.rs#L220) timeout (for some transactions) should also be larger …
> Retry on rpc timeout response

- primitives/src/lib.rs
> Modify DecimalsLookup trait, add PINK, HDX, vDOT to decimals list

- .cargo/config.toml
- Cargo.lock
- clients/README.md
- clients/runner/Cargo.toml
- clients/runtime/Cargo.toml
- clients/runtime/client/Cargo.toml
- clients/service/Cargo.toml
- clients/stellar-relay-lib/Cargo.toml
- clients/stellar-relay-lib/examples/connect.rs
- clients/stellar-relay-lib/src/config.rs
- clients/stellar-relay-lib/src/connection/authentication/certificate.rs
- clients/stellar-relay-lib/src/connection/connector/connector.rs
- clients/stellar-relay-lib/src/connection/connector/message_handler.rs
- clients/stellar-relay-lib/src/connection/connector/message_reader.rs
- clients/stellar-relay-lib/src/connection/connector/message_sender.rs
- clients/stellar-relay-lib/src/connection/error.rs
- clients/stellar-relay-lib/src/connection/handshake.rs
- clients/stellar-relay-lib/src/connection/helper.rs
- clients/stellar-relay-lib/src/connection/hmac.rs
- clients/stellar-relay-lib/src/connection/xdr_converter.rs
- clients/stellar-relay-lib/src/overlay.rs
- clients/vault/Cargo.toml
- clients/vault/src/main.rs
- clients/vault/src/oracle/collector/collector.rs
- clients/vault/src/oracle/collector/handler.rs
- clients/vault/src/system.rs
- clients/wallet/Cargo.toml
- clients/wallet/src/horizon/horizon.rs
- clients/wallet/src/resubmissions.rs
- clients/wallet/src/stellar_wallet.rs
This does not completely close #512, but it helps with tracking.
But if we can see which threads have been running the longest; which ones are idle for a long time, it could help determine where/when a vault gets stuck.
The [`tokio-console`](https://docs.rs/tokio-console/latest/tokio_console/) is described as:
> a debugging and profiling tool for asynchronous Rust applications, which collects and displays in-depth diagnostic data on the asynchronous tasks, resources, and operations in an application. 
^ From using tokio-console,  a zombie task was found.
When the vault restarts, it shuts down all running tasks except for 1:
https://github.com/pendulum-chain/spacewalk/blob/e7a672ba1e21c98a70df30a6ee458317951dd597/clients/wallet/src/resubmissions.rs#L40-L47
<br>
Aside from this, I found out …
> Allow Tokio Console support

- pallets/redeem/src/benchmarking.rs
Required to [fix](https://github.com/pendulum-chain/pendulum/pull/489#issuecomment-2346739621) benchmark when run for pendulum runtime.
> increase amount redeemed in benchmark test.

- clients/wallet/src/horizon/responses.rs
The presence of this field causes that the response cannot be decode correctly while still interpreted as a success, leading to downstream problems
> Remove deprecated response field.

- Cargo.lock
- clients/stellar-relay-lib/examples/connect.rs
This is required because the SCP types changed again and the vault is otherwise not able to decode archived entries for transaction sets. This was fixed in https://github.com/pendulum-chain/substrate-stellar-sdk/pull/38 and is available on the latest version of the `polkadot-v1.1.0` branch.
> Update to latest rev of substrate-stellar-sdk
